### ISSUE TITLE
Error in Trinity Network Explorer

### ISSUE THREAD

**Issue by namnhfreelancer** [trinity-project/trinity#72]
![image](https://user-images.githubusercontent.com/12831283/47715640-e4ee3900-dc72-11e8-82f3-3572b8b2dc0e.png)

I had try setup a node and channel in Trinity Neo Test Net. 
In console Log, It had been done.
But I can't see my node and channel in rinity Network Explorer http://texplorer.trinity.ink:7035/

**Comment by namnhfreelancer** [comment]
@zhuofanxu @zhangguangfeng @pigxo @xiaoji06

**Comment by yilwhust** [comment]
@zhuofanxu @zhangguangfeng @pigxo @xiaoji06,  the issue is related with trinity NEO was broken temporarily due to system updating.  its include updating domain name of server node and optimizing gateway topology group etc.  we will complete these work as soon as possible.  
thank you for your continued attention and support trinity

**Comment by namnhfreelancer** [comment]
Thank u for infomation

**Comment by yilwhust** [comment]
@zhuofanxu @zhangguangfeng @pigxo @xiaoji06 , Trinity NEO Test net had updated,  now  there is not deposit limit for create channel.  welcome to use trinity NEO continually

**Comment by namnhfreelancer** [comment]
> 
> 
> @zhuofanxu @zhangguangfeng @pigxo @xiaoji06 , Trinity NEO Test net had updated, now there is not deposit limit for create channel. welcome to use trinity NEO continually

Thanks for this update :D @yilwhust
